name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET_KEY: ThisIsAStrongCiJwtSecretKeyAtLeast32Chars

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore API
        run: dotnet restore src/SecureHelpdesk.Api/SecureHelpdesk.Api.csproj

      - name: Restore Unit Tests
        run: dotnet restore tests/SecureHelpdesk.Tests/SecureHelpdesk.Tests.csproj

      - name: Restore Integration Tests
        run: dotnet restore tests/SecureHelpdesk.IntegrationTests/SecureHelpdesk.IntegrationTests.csproj

      - name: Build API
        run: dotnet build src/SecureHelpdesk.Api/SecureHelpdesk.Api.csproj --no-restore --configuration Release

      - name: Build Unit Tests
        run: dotnet build tests/SecureHelpdesk.Tests/SecureHelpdesk.Tests.csproj --no-restore --configuration Release

      - name: Build Integration Tests
        run: dotnet build tests/SecureHelpdesk.IntegrationTests/SecureHelpdesk.IntegrationTests.csproj --no-restore --configuration Release

      - name: Test Unit Tests
        run: dotnet test tests/SecureHelpdesk.Tests/SecureHelpdesk.Tests.csproj --no-build --configuration Release --verbosity normal

      - name: Test Integration Tests
        run: dotnet test tests/SecureHelpdesk.IntegrationTests/SecureHelpdesk.IntegrationTests.csproj --no-build --configuration Release --verbosity normal
